#!/bin/bash
set -e
# Source debconf library
. /usr/share/debconf/confmodule

db_go


if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
  
		ping -c3 www.google.fr > /dev/null
		test="$?"
		if [ "$test" -eq 0 ];then
			RET="admin"
			db_get ctparental/httplogin || true
			export debconfloginhttp=$RET
			RET="admin"
			db_get ctparental/httppassword || true
			export debconfpassword=$RET
			
			CTparental -i -nodep -nomanuel
		fi
	
else
	
    echo "postinst called with unknown argument '$1'" 1>&2
    exit 0
fi

db_stop
exit 0
