#!/bin/bash
# Source debconf library.
. /usr/share/debconf/confmodule

# Show interface
db_go || true

ping -c3 www.google.fr > /dev/null
test=$?
if [ ! $test -eq 0 ];then
	db_input critical ctparental/erreurinternet
	db_go
	#echo "Connection internet requise!"
	exit 1
fi


rm -rf /usr/local/share/CTparental/
rm -f /usr/local/etc/CTparental-wl
rm -f /usr/local/etc/ossi.conf
rm -rf /usr/local/etc/CTparental*
rm -f /usr/local/etc/resolv.conf.sav
rm -f /etc/cron.d/CTparental*
rm -rf /usr/local/bin/CTadmin/
service cron restart
rm -f /usr/local/bin/CTparental.sh
mkdir -p /usr/local/bin


exit 0


