#!/bin/sh

set -e

. /usr/share/debconf/confmodule

#DEBCONF_DEBUG="developer"
# on ne demande le login/mot de pass que durant l'installation ou une reconfiguration de ctparental

if [ "$1" = "purge" ]; then
    db_purge
fi


