#!/bin/sh

set -e

. /usr/share/debconf/confmodule

#DEBCONF_DEBUG="developer"
# on ne demande le login/mot de pass que durant l'installation ou une reconfiguration de ctparental

if [ "$1" = "purge" ]; then
    db_purge
fi
if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then

while (true)
	do
			RET=""
			db_input critical ctparental/httplogin 
			db_go 
			db_get ctparental/httplogin 
			if [ "$(echo $RET | grep -E "^([a-zA-Z0-9])*$" | wc -m)" -ge 6  ];then 
					break
			fi	
	done
		
	while (true)
	do
		RET=""
		db_input high ctparental/httppassword 
	    db_go
		db_input high ctparental/httppassword2 
	    db_go
		db_get ctparental/httppassword 
		p1=$RET
		db_get ctparental/httppassword2 
		p2=$RET
		
			if [ $p1 = $p2 ] ; then
				if [ "$(echo "$p1" | grep -E "^([a-z0-9A-Z]|[&éè~#{}()ç_@à?.;:/\!,\$<>=£\%\])*$" | wc -m )" -ge 9 ] ; then
					RET=""
					break
				else
					db_input critical ctparental/httppassword_trop_simple 
					db_go
					db_set ctparental/httppassword "" 
					db_set ctparental/httppassword2 ""
					unset p1
					unset p2
				fi
			else
				db_input critical ctparental/httppassword_non_ident 
				db_go
				db_set ctparental/httppassword "" 
				db_set ctparental/httppassword2 ""
				
				unset p1
				unset p2
			fi

	done
	

fi

