#!/bin/sh

set -e

. /usr/share/debconf/confmodule

#DEBCONF_DEBUG="developer"
# on ne demande le login/mot de pass que durant l'installation ou une reconfiguration de ctparental
if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
while (true)
do
		RET=""
		db_input critical ctparental/httplogin || true
		db_go
		db_get ctparental/httplogin
		RET="$(echo $RET | grep -E "^([a-zA-Z0-9])*$")"
		if [ "${#RET}" -ge 5  ];then 
				break
		else
			db_input critical ctparental/httplogin_erreur
			db_purge
			db_go
		fi	
done
	
while (true)
do
		RET=""
		db_input critical ctparental/httppassword || true
	    db_go
		db_input critical ctparental/httppassword2 || true
	    db_go
		db_get ctparental/httppassword
		p1=$RET
		RET=""
		db_get ctparental/httppassword2
		p2=$RET
		RET=""
			if [ $p1 = $p2 ] ; then
				p1="$(echo "$p1" | grep -E "^([a-z0-9A-Z]|[&éè~#{}()ç_@à?.;:/\!,\$<>=£\%\])*$")"
				if [ "${#p1}" -ge 8 ] ; then
					p1=""
					p2=""
					db_go
					break
				else
					db_input critical ctparental/httppassword_trop_simple
					db_purge
					p1=""
					p2=""
				fi
			else
				db_input critical ctparental/httppassword_non_ident
				db_purge
				p1=""
				p2=""
			fi

	done
	

fi

#DEBHELPER#
