#!/bin/bash
#DEBHELPER#
set -e
# Source debconf library.
. /usr/share/debconf/confmodule

# Show interface
db_go || true

ping -c3 www.google.fr > /dev/null
test="$?"
if [ ! "$test" -eq 0 ];then
	db_input critical ctparental/erreurinternet
	db_go
	db_purge
else
	while (true)
	do
			RET=""
			db_input critical ctparental/httplogin || true
			db_go
			db_get ctparental/httplogin
			if [ "$(echo $RET | grep -E "^([a-zA-Z0-9])*$" | wc -m)" -ge 6  ];then 
					break
			fi	
	done
		
	while (true)
	do
		RET=""
		db_input critical ctparental/httppassword || true
	    db_go
		db_input critical ctparental/httppassword2 || true
	    db_go
		db_get ctparental/httppassword
		p1=$RET
		RET=""
		db_get ctparental/httppassword2
		p2=$RET
		RET=""
			if [ $p1 = $p2 ] ; then
				if [ "$(echo "$p1" | grep -E "^([a-z0-9A-Z]|[&éè~#{}()ç_@à?.;:/\!,\$<>=£\%\])*$" | wc -m )" -ge 9 ] ; then
					p1=""
					p2=""
					db_go
					break
				else
					db_input critical ctparental/httppassword_trop_simple
					p1=""
					p2=""
				fi
			else
				db_input critical ctparental/httppassword_non_ident
				p1=""
				p2=""
			fi

	done

	# Fetching configuration from debconf
	RET=""
	db_get ctparental/httplogin 
	export debconfloginhttp="$RET"
	RET="" 
	db_get ctparental/httppassword
	export debconfpassword="$RET"
	RET=""
	db_purge
    CTparental -i -nodep -nomanuel  
fi
exit 0
