#!/bin/sh
SED="/bin/sed -i"
echo " génération Blacklist pour ubound"
uboundfile=service.conf

cat << EOF > $uboundfile 
# Configuration file for "unbound with blackhole"
# Inclusion de la blacklist <domains> de Toulouse dans la configuration
server:
# verbosity level 0-4 of logging
verbosity: 0
# if you want to log to a file use
#logfile: "C:\unbound.log"

# more outgoing connections
# depends on number of cores: 1024/cores - 50
num-threads: 2
outgoing-range: 450  # when thread = 2
outgoing-num-tcp: 35
incoming-num-tcp: 35
num-queries-per-thread: 225  # when thread = 2
interface: 127.0.0.1
access-control: 127.0.0.0/8 allow
port: 53
do-ip4: yes
do-ip6: no
do-udp: yes
do-tcp: yes
hide-identity: yes
hide-version: yes
forward-zone:
name: "."
forward-addr: 8.8.8.8 # DNS googles peut ètre remplacé par les DNS fai ou autres DNS accesible de votre réseaux
#forward-addr: 8.8.8.8 # DNS2
server:
EOF

FILE_tmp=tmpfile
FILE_tmp2=tmpfile2

cat /etc/CTparental/blacklist-enabled/* | sed -e "s/address=\///g" | sed -e "s/^\.\{1,10\}//g" | grep -v "127.0.0.10"  | grep -v "#" | sort -u > "$FILE_tmp"

while read line
do
domain=$(echo $line | cut -d"/" -f1)
ip=$(echo $line | cut -d"/" -f2)
{
echo "local-zone: \"$domain\" redirect" 
echo "local-data: \"$domain A $ip\""
} >> $FILE_tmp2
done < "$FILE_tmp"

cat "$FILE_tmp2" >> $uboundfile 

cat /etc/CTparental/blacklist-enabled/* | sed -e "s/address=\///g" | sed -e "s/^\.\{1,10\}//g" | grep "127.0.0.10" | sed -e "s/\/127.0.0.10//g" | grep -v "#" | sort -u > "$FILE_tmp"
$SED "s?.*?local-zone: \"&\" redirect \nlocal-data: \"& A 127.0.0.10\"?g" "$FILE_tmp" # Mise en forme unbound des listes noires
cat  "$FILE_tmp" >> $uboundfile 
rm -f $FILE_tmp
rm -f $FILE_tmp2
